tools:

#  - name: binny
#    version:
#      # can be 'main', 'latest', or a specific version
#      want: v0.1.0
#      method: github-release
#    method: go-install
#    with:
#      module: github.com/anchore/binny
#      path: cmd/binny

  - name: quill
    version:
      want: v0.4.1
    method: github-release
    with:
      repo: anchore/quill

  - name: chronicle
    version:
      want: v0.7.0
    method: github-release
    with:
      repo: anchore/chronicle

  - name: gosimports
    version:
      want: v0.3.8
    method: github-release
    with:
      repo: rinchsan/gosimports

  - name: glow
    version:
      want: v1.5.1
    method: github-release
    with:
      repo: charmbracelet/glow

  - name: goreleaser
    version:
      want: v1.20.0
    method: github-release
    with:
      repo: goreleaser/goreleaser

  - name: golangci-lint
    version:
      want: v1.54.2
    method: github-release
    with:
      repo: golangci/golangci-lint

  - name: bouncer
    version:
      want: v0.4.0
    method: github-release
    with:
      repo: wagoodman/go-bouncer

  - name: task
    version:
      want: v3.29.1
    method: github-release
    with:
      repo: go-task/task
