tools:
  - name: binny
    version:
      # since the module is ., "current" means whatever is checked out
      want: current
    method: go-install
    with:
      # aka: github.com/anchore/binny, without going through github / goproxy (stay local)
      module: .
      entrypoint: cmd/binny
      ldflags:
       - -X main.version={{ .Version }}
       - -X main.gitCommit={{ .Version }}
       - -X main.gitDescription={{ .Version }}
       # note: sprig functions are available: http://masterminds.github.io/sprig/
       - -X main.buildDate={{ now | date "2006-01-02T15:04:05Z07:00" }}

  - name: gh
    version:
      want: v2.33.0
    method: github-release
    with:
      repo: cli/cli

  - name: quill
    version:
      want: v0.4.1
    method: github-release
    with:
      repo: anchore/quill

  - name: chronicle
    version:
      want: v0.7.0
    method: github-release
    with:
      repo: anchore/chronicle

  - name: gosimports
    version:
      want: v0.3.8
    method: github-release
    with:
      repo: rinchsan/gosimports

  - name: glow
    version:
      want: v1.5.1
    method: github-release
    with:
      repo: charmbracelet/glow

  - name: goreleaser
    version:
      want: v1.20.0
    method: github-release
    with:
      repo: goreleaser/goreleaser

  - name: golangci-lint
    version:
      want: v1.54.2
    method: github-release
    with:
      repo: golangci/golangci-lint

  - name: bouncer
    version:
      want: v0.4.0
    method: github-release
    with:
      repo: wagoodman/go-bouncer

  - name: task
    version:
      want: v3.29.1
    method: github-release
    with:
      repo: go-task/task
