permit:
  - BSD.*
  - CC0.*
  - MIT.*
  - Apache.*
  - MPL.*
  - ISC
  - WTFPL

ignore-packages:
  # from: https://github.com/xi2/xz/blob/master/LICENSE
  # All these files have been put into the public domain.
  # You can do whatever you want with these files.
  - github.com/xi2/xz

  # crypto/internal/boring is released under the openSSL license as a part of the Golang Standard Libary
  - crypto/internal/boring

  # https://github.com/sorairolake/lzip-go/blob/fef65de9b5037fff09499b582712e8411d347249/go.sum.license#L3
  # has `SPDX-License-Identifier: Apache-2.0 OR MIT`, both of which are acceptable
  - github.com/sorairolake/lzip-go
